### ISSUE TITLE
TruncatedChunkException thrown

### ISSUE THREAD

**Issue by msimonin** [snoozesoftware/snoozeclient#2]
When visualizing the hierarchy (snoozeclient visualize) TruncatedChunkException is thrown from time to time ...

[WARN ] |févr. 01 12:31:28| [Thread-1] org.restlet  - Unable to convert a [application/json] representation into an object of class org.inria.myriads.snoozecommon.communication.groupmanager.repository.GroupLeaderRepositoryInformation
org.apache.http.TruncatedChunkException: Truncated chunk ( expected size: 2085; actual size: 1997)
  at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:182)
  at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:138)
  at java.io.FilterInputStream.read(FilterInputStream.java:133)
  at java.io.FilterInputStream.read(FilterInputStream.java:133)
  at java.io.PushbackInputStream.read(PushbackInputStream.java:186)
  at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.loadMore(UTF8StreamJsonParser.java:174)
  at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parserNumber2(UTF8StreamJsonParser.java:1246)
  at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.parseNumberText(UTF8StreamJsonParser.java:1216)
  at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:786)
  at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:674)
  at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:220)
  at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:203)
  at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:23)
  at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:375)
  at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:98)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:308)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
  at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:429)
  at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:310)
  at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
  at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:375)
  at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:98)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:308)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
  at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:429)
  at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:310)
  at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
  at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:375)
  at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:98)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:308)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
  at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:226)
  at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:203)
  at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:23)
  at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:375)
  at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:98)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:308)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
  at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:429)
  at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:310)
  at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
  at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:375)
  at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:98)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:308)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
  at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:226)
  at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:203)
  at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:23)
  at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:375)
  at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:98)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:308)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
  at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1206)
  at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:788)
  at org.restlet.ext.jackson.JacksonRepresentation.getObject(JacksonRepresentation.java:255)
  at org.restlet.ext.jackson.JacksonConverter.toObject(JacksonConverter.java:234)
  at org.restlet.service.ConverterService.toObject(ConverterService.java:170)
  at org.restlet.resource.Resource.toObject(Resource.java:828)
  at org.restlet.engine.resource.ClientInvocationHandler.invoke(ClientInvocationHandler.java:268)
  at $Proxy7.getCompleteHierarchy(Unknown Source)
  at org.inria.myriads.snoozecommon.communication.rest.api.impl.RESTletBootstrapCommunicator.getCompleteHierarchy(RESTletBootstrapCommunicator.java:118)
  at org.inria.myriads.snoozeclient.util.BootstrapUtilis.getCompleteHierarchy(BootstrapUtilis.java:170)
  at org.inria.myriads.snoozeclient.systemtree.SystemTreeVisualizer.getCompleteHierarchy(SystemTreeVisualizer.java:161)
  at org.inria.myriads.snoozeclient.systemtree.SystemTreeVisualizer.startPolling(SystemTreeVisualizer.java:191)
  at org.inria.myriads.snoozeclient.systemtree.SystemTreeVisualizer.access$500(SystemTreeVisualizer.java:89)
  at org.inria.myriads.snoozeclient.systemtree.SystemTreeVisualizer$3$1.run(SystemTreeVisualizer.java:292)

**Comment by msimonin** [comment]
It's seem related to restlet 2.2-SNAPSHOT. 
Need confirmation...
